/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedOutreachComposerIndexRouteImport } from './routes/_authenticated/outreach-composer/index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/index'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'
import { Route as AuthenticatedSettingsLogsRouteImport } from './routes/_authenticated/settings/logs'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsComplianceRouteImport } from './routes/_authenticated/settings/compliance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReportsGrowthRouteImport } from './routes/_authenticated/reports/growth'
import { Route as AuthenticatedReportsEngagementRouteImport } from './routes/_authenticated/reports/engagement'
import { Route as AuthenticatedReportsDeliverabilityRouteImport } from './routes/_authenticated/reports/deliverability'
import { Route as AuthenticatedOutreachComposerNewRouteImport } from './routes/_authenticated/outreach-composer/new'
import { Route as AuthenticatedEmailSentRouteImport } from './routes/_authenticated/email/sent'
import { Route as AuthenticatedEmailInboxRouteImport } from './routes/_authenticated/email/inbox'
import { Route as AuthenticatedEmailDraftsRouteImport } from './routes/_authenticated/email/drafts'
import { Route as AuthenticatedContactsCollectionsRouteImport } from './routes/_authenticated/contacts/collections'
import { Route as AuthenticatedContactsContactIdRouteImport } from './routes/_authenticated/contacts/$contactId'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns/new'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns/$campaignId'
import { Route as AuthenticatedOutreachComposerTemplateIdEditRouteImport } from './routes/_authenticated/outreach-composer/$templateId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutreachComposerIndexRoute =
  AuthenticatedOutreachComposerIndexRouteImport.update({
    id: '/outreach-composer/',
    path: '/outreach-composer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLogsRoute =
  AuthenticatedSettingsLogsRouteImport.update({
    id: '/settings/logs',
    path: '/settings/logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsComplianceRoute =
  AuthenticatedSettingsComplianceRouteImport.update({
    id: '/settings/compliance',
    path: '/settings/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsGrowthRoute =
  AuthenticatedReportsGrowthRouteImport.update({
    id: '/reports/growth',
    path: '/reports/growth',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsEngagementRoute =
  AuthenticatedReportsEngagementRouteImport.update({
    id: '/reports/engagement',
    path: '/reports/engagement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsDeliverabilityRoute =
  AuthenticatedReportsDeliverabilityRouteImport.update({
    id: '/reports/deliverability',
    path: '/reports/deliverability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutreachComposerNewRoute =
  AuthenticatedOutreachComposerNewRouteImport.update({
    id: '/outreach-composer/new',
    path: '/outreach-composer/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailSentRoute = AuthenticatedEmailSentRouteImport.update({
  id: '/email/sent',
  path: '/email/sent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailInboxRoute = AuthenticatedEmailInboxRouteImport.update({
  id: '/email/inbox',
  path: '/email/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailDraftsRoute =
  AuthenticatedEmailDraftsRouteImport.update({
    id: '/email/drafts',
    path: '/email/drafts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsCollectionsRoute =
  AuthenticatedContactsCollectionsRouteImport.update({
    id: '/contacts/collections',
    path: '/contacts/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsContactIdRoute =
  AuthenticatedContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutreachComposerTemplateIdEditRoute =
  AuthenticatedOutreachComposerTemplateIdEditRouteImport.update({
    id: '/outreach-composer/$templateId/edit',
    path: '/outreach-composer/$templateId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/contacts/collections': typeof AuthenticatedContactsCollectionsRoute
  '/email/drafts': typeof AuthenticatedEmailDraftsRoute
  '/email/inbox': typeof AuthenticatedEmailInboxRoute
  '/email/sent': typeof AuthenticatedEmailSentRoute
  '/outreach-composer/new': typeof AuthenticatedOutreachComposerNewRoute
  '/reports/deliverability': typeof AuthenticatedReportsDeliverabilityRoute
  '/reports/engagement': typeof AuthenticatedReportsEngagementRoute
  '/reports/growth': typeof AuthenticatedReportsGrowthRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/compliance': typeof AuthenticatedSettingsComplianceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/outreach-composer/': typeof AuthenticatedOutreachComposerIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/outreach-composer/$templateId/edit': typeof AuthenticatedOutreachComposerTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/contacts/collections': typeof AuthenticatedContactsCollectionsRoute
  '/email/drafts': typeof AuthenticatedEmailDraftsRoute
  '/email/inbox': typeof AuthenticatedEmailInboxRoute
  '/email/sent': typeof AuthenticatedEmailSentRoute
  '/outreach-composer/new': typeof AuthenticatedOutreachComposerNewRoute
  '/reports/deliverability': typeof AuthenticatedReportsDeliverabilityRoute
  '/reports/engagement': typeof AuthenticatedReportsEngagementRoute
  '/reports/growth': typeof AuthenticatedReportsGrowthRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/compliance': typeof AuthenticatedSettingsComplianceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/outreach-composer': typeof AuthenticatedOutreachComposerIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/outreach-composer/$templateId/edit': typeof AuthenticatedOutreachComposerTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/_authenticated/contacts/collections': typeof AuthenticatedContactsCollectionsRoute
  '/_authenticated/email/drafts': typeof AuthenticatedEmailDraftsRoute
  '/_authenticated/email/inbox': typeof AuthenticatedEmailInboxRoute
  '/_authenticated/email/sent': typeof AuthenticatedEmailSentRoute
  '/_authenticated/outreach-composer/new': typeof AuthenticatedOutreachComposerNewRoute
  '/_authenticated/reports/deliverability': typeof AuthenticatedReportsDeliverabilityRoute
  '/_authenticated/reports/engagement': typeof AuthenticatedReportsEngagementRoute
  '/_authenticated/reports/growth': typeof AuthenticatedReportsGrowthRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/compliance': typeof AuthenticatedSettingsComplianceRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/outreach-composer/': typeof AuthenticatedOutreachComposerIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/outreach-composer/$templateId/edit': typeof AuthenticatedOutreachComposerTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/calendar'
    | '/dashboard'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/contacts/$contactId'
    | '/contacts/collections'
    | '/email/drafts'
    | '/email/inbox'
    | '/email/sent'
    | '/outreach-composer/new'
    | '/reports/deliverability'
    | '/reports/engagement'
    | '/reports/growth'
    | '/settings/account'
    | '/settings/compliance'
    | '/settings/integrations'
    | '/settings/logs'
    | '/settings/team'
    | '/campaigns/'
    | '/contacts/'
    | '/outreach-composer/'
    | '/reports/'
    | '/outreach-composer/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/calendar'
    | '/dashboard'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/contacts/$contactId'
    | '/contacts/collections'
    | '/email/drafts'
    | '/email/inbox'
    | '/email/sent'
    | '/outreach-composer/new'
    | '/reports/deliverability'
    | '/reports/engagement'
    | '/reports/growth'
    | '/settings/account'
    | '/settings/compliance'
    | '/settings/integrations'
    | '/settings/logs'
    | '/settings/team'
    | '/campaigns'
    | '/contacts'
    | '/outreach-composer'
    | '/reports'
    | '/outreach-composer/$templateId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/contacts/$contactId'
    | '/_authenticated/contacts/collections'
    | '/_authenticated/email/drafts'
    | '/_authenticated/email/inbox'
    | '/_authenticated/email/sent'
    | '/_authenticated/outreach-composer/new'
    | '/_authenticated/reports/deliverability'
    | '/_authenticated/reports/engagement'
    | '/_authenticated/reports/growth'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/compliance'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/logs'
    | '/_authenticated/settings/team'
    | '/_authenticated/campaigns/'
    | '/_authenticated/contacts/'
    | '/_authenticated/outreach-composer/'
    | '/_authenticated/reports/'
    | '/_authenticated/outreach-composer/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outreach-composer/': {
      id: '/_authenticated/outreach-composer/'
      path: '/outreach-composer'
      fullPath: '/outreach-composer/'
      preLoaderRoute: typeof AuthenticatedOutreachComposerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/logs': {
      id: '/_authenticated/settings/logs'
      path: '/settings/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AuthenticatedSettingsLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/compliance': {
      id: '/_authenticated/settings/compliance'
      path: '/settings/compliance'
      fullPath: '/settings/compliance'
      preLoaderRoute: typeof AuthenticatedSettingsComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/growth': {
      id: '/_authenticated/reports/growth'
      path: '/reports/growth'
      fullPath: '/reports/growth'
      preLoaderRoute: typeof AuthenticatedReportsGrowthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/engagement': {
      id: '/_authenticated/reports/engagement'
      path: '/reports/engagement'
      fullPath: '/reports/engagement'
      preLoaderRoute: typeof AuthenticatedReportsEngagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/deliverability': {
      id: '/_authenticated/reports/deliverability'
      path: '/reports/deliverability'
      fullPath: '/reports/deliverability'
      preLoaderRoute: typeof AuthenticatedReportsDeliverabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outreach-composer/new': {
      id: '/_authenticated/outreach-composer/new'
      path: '/outreach-composer/new'
      fullPath: '/outreach-composer/new'
      preLoaderRoute: typeof AuthenticatedOutreachComposerNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email/sent': {
      id: '/_authenticated/email/sent'
      path: '/email/sent'
      fullPath: '/email/sent'
      preLoaderRoute: typeof AuthenticatedEmailSentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email/inbox': {
      id: '/_authenticated/email/inbox'
      path: '/email/inbox'
      fullPath: '/email/inbox'
      preLoaderRoute: typeof AuthenticatedEmailInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email/drafts': {
      id: '/_authenticated/email/drafts'
      path: '/email/drafts'
      fullPath: '/email/drafts'
      preLoaderRoute: typeof AuthenticatedEmailDraftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/collections': {
      id: '/_authenticated/contacts/collections'
      path: '/contacts/collections'
      fullPath: '/contacts/collections'
      preLoaderRoute: typeof AuthenticatedContactsCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/$contactId': {
      id: '/_authenticated/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outreach-composer/$templateId/edit': {
      id: '/_authenticated/outreach-composer/$templateId/edit'
      path: '/outreach-composer/$templateId/edit'
      fullPath: '/outreach-composer/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedOutreachComposerTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedContactsContactIdRoute: typeof AuthenticatedContactsContactIdRoute
  AuthenticatedContactsCollectionsRoute: typeof AuthenticatedContactsCollectionsRoute
  AuthenticatedEmailDraftsRoute: typeof AuthenticatedEmailDraftsRoute
  AuthenticatedEmailInboxRoute: typeof AuthenticatedEmailInboxRoute
  AuthenticatedEmailSentRoute: typeof AuthenticatedEmailSentRoute
  AuthenticatedOutreachComposerNewRoute: typeof AuthenticatedOutreachComposerNewRoute
  AuthenticatedReportsDeliverabilityRoute: typeof AuthenticatedReportsDeliverabilityRoute
  AuthenticatedReportsEngagementRoute: typeof AuthenticatedReportsEngagementRoute
  AuthenticatedReportsGrowthRoute: typeof AuthenticatedReportsGrowthRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsComplianceRoute: typeof AuthenticatedSettingsComplianceRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsLogsRoute: typeof AuthenticatedSettingsLogsRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedOutreachComposerIndexRoute: typeof AuthenticatedOutreachComposerIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedOutreachComposerTemplateIdEditRoute: typeof AuthenticatedOutreachComposerTemplateIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCampaignsCampaignIdRoute: AuthenticatedCampaignsCampaignIdRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedContactsContactIdRoute: AuthenticatedContactsContactIdRoute,
  AuthenticatedContactsCollectionsRoute: AuthenticatedContactsCollectionsRoute,
  AuthenticatedEmailDraftsRoute: AuthenticatedEmailDraftsRoute,
  AuthenticatedEmailInboxRoute: AuthenticatedEmailInboxRoute,
  AuthenticatedEmailSentRoute: AuthenticatedEmailSentRoute,
  AuthenticatedOutreachComposerNewRoute: AuthenticatedOutreachComposerNewRoute,
  AuthenticatedReportsDeliverabilityRoute:
    AuthenticatedReportsDeliverabilityRoute,
  AuthenticatedReportsEngagementRoute: AuthenticatedReportsEngagementRoute,
  AuthenticatedReportsGrowthRoute: AuthenticatedReportsGrowthRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsComplianceRoute: AuthenticatedSettingsComplianceRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsLogsRoute: AuthenticatedSettingsLogsRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedOutreachComposerIndexRoute:
    AuthenticatedOutreachComposerIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedOutreachComposerTemplateIdEditRoute:
    AuthenticatedOutreachComposerTemplateIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
